### ISSUE TITLE
New Modifier API: Capture from canvas directly without `AndroidView`

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/Capturable#100]
### Discussed in https://github.com/PatilShreyas/Capturable/discussions/98

<div type='discussions-op-text'>

<sup>Originally posted by **yschimke** June  8, 2023</sup>
Could Capturable use this alpha API to capture the image instead of an AndroidView?

https://cs.android.com/androidx/platform/frameworks/support/+/f60a1149f00d6cc5972e9bd4057eb4a15505b468:compose/ui/ui-graphics/samples/src/main/java/androidx/compose/ui/graphics/samples/DrawScopeSample.kt;l=131</div>

**Comment by yschimke** [comment]
https://twitter.com/riggaroo/status/1693961082761625825?t=kfgghffcZXsuhus0txy90w&s=19

Think you saw this already

**Comment by jsericksk** [comment]
I tested the code you put in the #103 and the problem with capturing scrollable content continues, even though you mentioned that the new API solved this problem. Is it really working for you? Is there anything else that needs to be done to make Column(Modifier.verticalScroll()) work? It also doesn't work with [documentation snippet](https://github.com/android/snippets/blob/main/compose/snippets/src/main/java/com/example/compose/snippets/graphics/AdvancedGraphicsSnippets.kt).

**Comment by PatilShreyas** [comment]
@jsericksk Yes, when I tested, it worked nicely. Can you share me a snippet or a sample?

**Comment by jsericksk** [comment]
Sorry, @PatilShreyas. I realized that when I was testing, I was applying Modifier.capturable() to the parent component and not to the capturable component directly, so I was only capturing the currently visible part. It's working normally now. Looking forward to the next release!

**Comment by PatilShreyas** [comment]
This issue has been fixed and released in version 2.0.0.
