### ISSUE TITLE
Possibility to capture a compostable without displaying it

### ISSUE THREAD

**Issue by Jeluchu** [PatilShreyas/Capturable#15]
Hello again!

Based on the issue that I have opened that when taking a screenshot in a LazyColumn the captured image is cut, I have come up with an idea.

I don't know if it could be done but I think it is a good suggestion, and it would be the ability to generate captures of the composables without the need to show them on the screen, that way as now, when pressing a button you would simply put as now the `controller.capture()` and previously have configured the Capturable with the Composable that you want to capture but without the need to be displayed in the view.

Again, many thanks in advance!

**Comment by PatilShreyas** [comment]
Thanks @Jeluchu for the suggestion

**Comment by PatilShreyas** [comment]
Need to think on this

**Comment by PatilShreyas** [comment]
Duplicate #13

**Comment by PatilShreyas** [comment]
This issue has been fixed and released in `v1.0.3`. Thanks!
