### ISSUE TITLE
.await() cannot be called inside a button onClick callback

### ISSUE THREAD

**Issue by lucanicoletti** [PatilShreyas/Capturable#156]
Following the documentation:
```kotlin
// Example: Capture the content when button is clicked
Button(onClick = {
    // Capture content
    val bitmapAsync = captureController.captureAsync()
    try {
        val bitmap = bitmapAsync.await()
        // Do something with `bitmap`.
    } catch (error: Throwable) {
        // Error occurred, do something.
    }
}) { ... }
```

This is not possible as, the function `await()` cannot be called inside the `onClick` callback. What's the workaround? Should the docs be updated?

**Comment by SchwartzLizer** [comment]
await() is suspend function 
use `val coroutineScope = rememberCoroutineScope() `
```
coroutineScope.launch {
    val bitmap = bitmapAsync.await()
}
```

**Comment by anuragdalia** [comment]
Add this to the top of your composable
`val scope = rememberCoroutineScope()`

and then try
// Example: Capture the content when button is clicked
Button(onClick = {
scope.launch{
    // Capture content
    val bitmapAsync = captureController.captureAsync()
    try {
        val bitmap = bitmapAsync.await()
        // Do something with `bitmap`.
    } catch (error: Throwable) {
        // Error occurred, do something.
    }
}
}) { ... }

**Comment by PatilShreyas** [comment]
Updated docs to avoid the confusion: https://github.com/PatilShreyas/Capturable/blob/master/README.md#3-capture-the-content
