### ISSUE TITLE
Not all elements are captured

### ISSUE THREAD

**Issue by Efimj** [PatilShreyas/Capturable#185]
lib version: 2.1.0

# I have a screen like this:

```
Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .allWindowInsetsPadding()
                .padding(vertical = 40.dp)
        ) {
            Column(
                modifier = Modifier
                    .capturable(captureController)
                    .fillMaxWidth()
                    .background(AppTheme.colors.background)
                    .padding(top = 40.dp, bottom = 70.dp)
                    .padding(horizontal = 10.dp)
            ) {
                Text(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(bottom = 20.dp),
                    text = stringResource(R.string.Statistics),
                    color = AppTheme.colors.text,
                    style = MaterialTheme.typography.displaySmall,
                    fontWeight = FontWeight.SemiBold,
                    maxLines = 1,
                    textAlign = TextAlign.Center
                )
                Column(
                    horizontalAlignment = Alignment.CenterHorizontally,
                    verticalArrangement = Arrangement.spacedBy(15.dp)
                ) {
                    statistics.map { StatisticsCard(it) }
                }
            }
        }
```

# I'm expecting a full screenshot like this:

![image](https://github.com/PatilShreyas/Capturable/assets/87390257/014b0e37-1b83-4c0e-b9c3-13fc89e52f39)

# But I only get part:

![image](https://github.com/PatilShreyas/Capturable/assets/87390257/1596c026-c7fc-447c-957d-b913518734ca)

**Comment by PatilShreyas** [comment]
Thanks for reporting the issue, getting this checked

**Comment by PatilShreyas** [comment]
@Efimj when exactly you're capturing this composable?

**Comment by PatilShreyas** [comment]
I tried to reproduce the issue in my sample app with reference to a code snippet you shared. But it worked well for me without any issues. I'll need exact reproducing sample code to diagnose this issue. Can you please share a sample project with me where we'll be able to see the issue?

[Screen_recording_20240706_211637.webm](https://github.com/PatilShreyas/Capturable/assets/19620536/d19da970-02f7-495e-8019-94ba2730c4c5)

**Comment by Efimj** [comment]
@PatilShreyas Hey 👋 
I use it in the code here:

https://github.com/Efimj/Shkiper/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fjobik%2Fshkiper%2Fscreens%2Fstatistics%2FStatisticsScreen.kt

**Comment by Efimj** [comment]
### After updating libraries:

```
navigation RuntimeKtx = "2.8.0-beta03" => navigation Runtime Ktx = "2.8.0-beta04"
foundation = "1.7.0-beta02" => foundation = "1.7.0-beta04"
```

Everything worked
_thanks for your library_ ⭐
