### ISSUE TITLE
Not able to capture Modifier.blur()

### ISSUE THREAD

**Issue by Jithin-Jude** [PatilShreyas/Capturable#186]
I was trying to capture an Image composable modified with blur(). But it's not working so I had to use the lagacy RenderScript blurring method. Any idea why it's not capturing jepack compose blur?

**Comment by PatilShreyas** [comment]
Thanks for reporting the issue, will check this issue. Do you have a sample code?

**Comment by Jithin-Jude** [comment]
I was doing something similar to this:

val captureController = rememberCaptureController()
fun MyView(captureController: CaptureController){
Image(
            bitmap = it.asImageBitmap(),
            contentDescription = null,
            modifier = Modifier
                .fillMaxSize()
                .blur(16.dp)
        )
}

**Comment by PatilShreyas** [comment]
I just tried it and found that if you use `blur()` modifier after `capturable()` one, it works, so closing this issue.
