### ISSUE TITLE
java.lang.IllegalStateException: Software rendering doesn't support hardware bitmaps

### ISSUE THREAD

**Issue by sjqnice** [PatilShreyas/Capturable#188]
when I use it, it crashed with IllegalStateException
<img width="969" alt="image" src="https://github.com/PatilShreyas/Capturable/assets/14270796/eafab8a4-e265-41a1-af85-19b7f8f3ac90">

**Comment by PatilShreyas** [comment]
This was already discussed here: #180.
Are you loading an image from the network? Disable hardware rendering for the area which is involved in capturing the bitmap.

**Comment by sjqnice** [comment]
I use Coil loading image. Adding the following resolved the error: .allowHardware(false). Thank you for the response!
