### ISSUE TITLE
Resize the image

### ISSUE THREAD

**Issue by hliosdja** [PatilShreyas/Capturable#190]
Hi, I'm trying to resize the image to fit my requirements however, it seems like its fixed to a certain size. Tried scaling it via createScaledBitmap method but it seems it's not working.

How can I resize the image? any help with this will be appreciated

**Comment by PatilShreyas** [comment]
@hliosdja You can use the Bitmap API like this

```kotlin
val originalBitmap: Bitmap = ...
val resizedBitmap = Bitmap.createScaledBitmap(originalBitmap, newWidth, newHeight, false)
```

**Comment by hliosdja** [comment]
> @hliosdja You can use the Bitmap API like this
> 
> ```kotlin
> val originalBitmap: Bitmap = ...
> val resizedBitmap = Bitmap.createScaledBitmap(originalBitmap, newWidth, newHeight, false)
> ```

thanks for the reply, will try again this method. there might be something im missing.
