### ISSUE TITLE
Captures only the visible part in screen

### ISSUE THREAD

**Issue by ShankarKakumani** [PatilShreyas/Capturable#31]
I am using LazyColumn, where I have several items.

Each Item have a button to capture that specific item.

If I click the button on a item, which is partially visible on the screen, it's only capturing the visible part.

Is there a way, where I can capture the complete item, even if it's partially visible.

**Comment by PatilShreyas** [comment]
Thanks for reporting the issue @ShankarKakumani. Ideally, this shouldn't happen because I also tested this recently and it's working fine for me. The item you are capturing, what are the contents of that item? What exactly you're showing in it?

**Comment by ShankarKakumani** [comment]
LazyColumn Part
`            LazyColumn( state = listState,
                modifier = Modifier
                    .fillMaxSize()
                    .constrainAs(lazyColumn) {
                        top.linkTo(legends.bottom, 10.dp)
                        bottom.linkTo(parent.bottom)
                        start.linkTo(parent.start)
                        end.linkTo(parent.end)
                        height = Dimension.fillToConstraints
                        width = Dimension.fillToConstraints
                    }
            ) {

                viewModel.recentTripData.value.data?.recentTripsList?.forEachIndexed { index, recentTripsDomain ->
                    item {
                        MainCard(recentTripsDomain, index, viewModel)
                    }
                }

            }`
            
            
            
            
            
            MainCard
            
            
            `    @Composable
    fun MainCard(domain: RecentTripsDomain?, index: Int, viewModel: RecentTripViewModel) {
        val controller = rememberCaptureController()
        val topPadding = if (index == 0) ScreenWidth.getCalculatedDp(20).dp else ScreenWidth.getCalculatedDp(38).dp

        ConstraintLayout(
            modifier = Modifier.padding(
                start = ScreenWidth.getCalculatedDp(25).dp,
                end = ScreenWidth.getCalculatedDp(25).dp,
                top = topPadding
            )

        ) {

            val (shareButton) = createRefs()
            val coroutineScope = rememberCoroutineScope()

            Capturable(
                controller = controller,
                onCaptured = { bitmap, error ->
                    viewModel.getNavigator()?.shareTripCardImage(bitmap?.asAndroidBitmap())
                }
            ) {
                MainCardContent(controller, viewModel, index = index, domain)
            }

            IconButton(
                onClick = {
                    coroutineScope.launch {
                        controller.capture()
                    }
                },
                modifier = Modifier
                    .size(ScreenWidth.getCalculatedDp(26).dp)
                    .constrainAs(shareButton)
                    {
                        top.linkTo(parent.top, ScreenWidth.getCalculatedDp(13).dp)
                        end.linkTo(parent.end, ScreenWidth.getCalculatedDp(12).dp)
                        width = Dimension.wrapContent
                        height = Dimension.wrapContent
                    }) {
                Image(
                    painter = painterResource(id = getAppIcons().shareIcon),
                    contentDescription = "Share Icon",
                )
            }

        }

    }`
    
    
    MainCardContent
    
    `    @OptIn(ExperimentalCoilApi::class)
    @Composable
    private fun MainCardContent(
        controller: CaptureController,
        viewModel: RecentTripViewModel,
        index: Int,
        domain: RecentTripsDomain?
    ) {
        val pathEffect = PathEffect.dashPathEffect(floatArrayOf(20f, 20f), 0f)
        ConstraintLayout(
            modifier = Modifier
                .clip(RoundedCornerShape(23.dp))
                .background(
                    color = getAppColors().batteryScreenCardBackground,
                    RoundedCornerShape(23.dp)
                )
                .fillMaxWidth()

        ) {

            val (
                map_image,
                trip_kms_mins, trip_time,
                dotted_line,
                markers, map_pin, address_column,
                separator,
                max_speed, avg_speed, energy_used, efficiency,
                max_speed_value, avg_speed_value, energy_used_value, efficiency_value,
            ) = createRefs()

            val (progressBar, background, shareButton, map_legends_container, startDestination, endDestination) = createRefs()

            val painter = rememberImagePainter(
                data = domain?.tripSummary?.tripSnapshot ?: ""
            )

            val painterState = painter.state

            Image(
                modifier = Modifier
                    .constrainAs(map_image) {
                        start.linkTo(parent.start, 4.dp)
                        end.linkTo(parent.end, 4.dp)
                        top.linkTo(parent.top, 4.dp)
                        width = Dimension.fillToConstraints
                    }
                    .height(ScreenWidth.getCalculatedDp(111).dp)
                    .clip(RoundedCornerShape(20.dp)),
                painter = painter,
                contentDescription = "",
                contentScale = ContentScale.FillBounds
            )


            Row(
                modifier = Modifier
                    .constrainAs(map_legends_container) {

                        bottom.linkTo(map_image.bottom, 8.dp)
                        end.linkTo(map_image.end, 12.dp)
                    }
                    .background(
                        Color.White,
                        RoundedCornerShape(8.dp)
                    )
                    .border(
                        color = getAppColors().cardBorder,
                        width = 0.5.dp,
                        shape = RoundedCornerShape(8.dp)
                    )
                    .height(24.dp),
//                horizontalArrangement = Arrangement.SpaceAround,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Spacer(modifier = Modifier.width(10.dp))

                domain?.tripSummary?.tripMode?.ecoDistance?.let {
                    MapLegendData("eco", it)
                }
                domain?.tripSummary?.tripMode?.rideDistance?.let {
                    MapLegendData("ride", it)
                }
                domain?.tripSummary?.tripMode?.dashDistance?.let {
                    MapLegendData("dash", it)
                }
                domain?.tripSummary?.tripMode?.sonicDistance?.let {
                    MapLegendData("sonic", it)
                }

                Spacer(modifier = Modifier.width(5.dp))
            }

            Text(
                modifier = Modifier.constrainAs(trip_kms_mins) {
                    top.linkTo(map_image.bottom, 12.dp)
                    start.linkTo(parent.start, 16.dp)
                },
                text = buildAnnotatedString {
                    append(domain?.tripSummary?.tripTotalDistance ?: "")
                    append(" Kms,")
                    append(" " + domain?.tripSummary?.tripDuration ?: "")
                    append(" mins")
                },
                fontFamily = getAppFonts().inter,
                fontWeight = FontWeight.SemiBold,
                fontSize = 14.sp,
                color = Color.White
            )

            val date = DateTimeParser.parseFromTS(domain?.epochTime?.toLong())
            val time = DateTimeParser.getTimeFromTs(domain?.epochTime?.toLong())
            Text(
                modifier = Modifier.constrainAs(trip_time) {
                    top.linkTo(map_image.bottom, 15.dp)
                    end.linkTo(parent.end, 16.dp)
                },
                text = buildAnnotatedString {
                    append(date)
                    append(" $time")
                },
                fontFamily = getAppFonts().inter,
                fontWeight = FontWeight.Medium,
                fontSize = 12.sp,
                color = Color.White
            )

//            Canvas(
//                Modifier
//                    .constrainAs(dotted_line) {
//                        width = Dimension.fillToConstraints
//                        top.linkTo(trip_kms_mins.bottom, 10.dp)
//                        start.linkTo(parent.start, 16.dp)
//                        end.linkTo(parent.end, 16.dp)
//                    }
//                    .fillMaxWidth()
//                    .height(1.dp)) {
//                drawLine(
//                    color = Color(0xFFC9C9C9),
//                    start = Offset(0f, 0f),
//                    end = Offset(size.width, 0f),
//                    pathEffect = pathEffect
//                )
//            }
            Box(
                Modifier
                    .constrainAs(dotted_line) {
                        width = Dimension.fillToConstraints
                        top.linkTo(trip_kms_mins.bottom, 10.dp)
                        start.linkTo(parent.start, 16.dp)
                        end.linkTo(parent.end, 16.dp)
                    }
                    .height(1.dp)
                    .fillMaxWidth()
                    .background(color = getAppColors().cardBorder, shape = DottedShape(step = 10.dp))
            )


            Icon(
                painter = painterResource(id = getAppIcons().recentTripsLocationPointers),
                contentDescription = "Location Markers Icon",
                tint = Color.White,
                modifier = Modifier.constrainAs(markers) {
                    start.linkTo(parent.start, 30.dp)
                    top.linkTo(dotted_line.bottom, 17.dp)
                })



            Text(
                text = domain?.tripSummary?.tripPoint?.startPoint?.address
                    ?: "",
                fontSize = 11.sp,
                maxLines = 2,
                overflow = TextOverflow.Ellipsis,
                fontFamily = getAppFonts().inter,
                fontWeight = FontWeight.Medium,
                color = getAppColors().textInActiveColor,
                lineHeight = 16.sp,
                modifier = Modifier
                    .constrainAs(startDestination) {
                        start.linkTo(markers.end, 20.dp)
                        top.linkTo(dotted_line.bottom, 16.dp)
                        end.linkTo(parent.end, 16.dp)
                        width = Dimension.fillToConstraints
                    }
                    .defaultMinSize(minHeight = 32.dp)
            )


            Text(
                text = domain?.tripSummary?.tripPoint?.endPoint?.address ?: "",
                fontSize = 11.sp,
                maxLines = 2,
                overflow = TextOverflow.Ellipsis,
                fontFamily = getAppFonts().inter,
                fontWeight = FontWeight.Medium,
                color = getAppColors().textInActiveColor,
                lineHeight = 16.sp,
                modifier = Modifier
                    .constrainAs(endDestination) {
                        start.linkTo(markers.end, 20.dp)
                        top.linkTo(startDestination.bottom, 9.dp)
                        end.linkTo(parent.end, 16.dp)
                        width = Dimension.fillToConstraints
                    }
                    .defaultMinSize(minHeight = 32.dp)
            )



            Divider(modifier = Modifier
                .constrainAs(separator) {
                    top.linkTo(markers.bottom, 12.dp)
                    start.linkTo(parent.start)
                    end.linkTo(parent.end)
                    width = Dimension.fillToConstraints
                }
                .background(getAppColors().textInActiveColor))


            createHorizontalChain(max_speed, avg_speed, energy_used, efficiency)

            Text(
                modifier = Modifier.constrainAs(max_speed) {
                    start.linkTo(parent.start)
                    top.linkTo(separator.bottom, 10.dp)
                    end.linkTo(avg_speed.start)
                }, text = "Max. Speed",
                fontFamily = getAppFonts().inter,
                fontWeight = FontWeight.Medium,
                fontSize = 11.sp,
                color = getAppColors().textInActiveColor
            )

            Text(
                modifier = Modifier.constrainAs(max_speed_value) {
                    start.linkTo(max_speed.start)
                    top.linkTo(max_speed.bottom, 3.dp)
                    end.linkTo(max_speed.end)
                    bottom.linkTo(parent.bottom, 9.7.dp)
                },
                text = buildAnnotatedString {
                    withStyle(
                        style = SpanStyle(
                            fontWeight = FontWeight.SemiBold,
                            color = Color.White,
                            fontFamily = getAppFonts().inter,
                            fontSize = 12.sp,
                        )
                    ) {
                        append(domain?.tripSummary?.maxSpeed ?: "")
                    }
                    append(" km/h")
                },
                fontSize = 11.sp,
                fontWeight = FontWeight.Medium,
                fontFamily = getAppFonts().inter,
                color = Color.White
            )

            Text(
                modifier = Modifier.constrainAs(avg_speed) {
                    start.linkTo(max_speed.end)
                    top.linkTo(max_speed.top)
                    bottom.linkTo(max_speed.bottom)
                    end.linkTo(energy_used.start)
                }, text = "Avg. Speed",
                fontFamily = getAppFonts().inter,
                fontWeight = FontWeight.Medium,
                fontSize = 11.sp,
                color = getAppColors().textInActiveColor
            )

            Text(
                modifier = Modifier.constrainAs(avg_speed_value) {
                    start.linkTo(avg_speed.start)
                    top.linkTo(avg_speed.bottom, 3.dp)
                    end.linkTo(avg_speed.end)
                    bottom.linkTo(parent.bottom, 9.7.dp)
                },
                text =
                buildAnnotatedString {
                    withStyle(
                        style = SpanStyle(
                            fontWeight = FontWeight.SemiBold,
                            color = Color.White,
                            fontFamily = getAppFonts().inter,
                            fontSize = 12.sp,
                        )
                    ) {
                        append(domain?.tripSummary?.averageSpeed ?: "")
                    }
                    append(" km/h")
                },
                fontSize = 11.sp,
                fontWeight = FontWeight.Medium,
                fontFamily = getAppFonts().inter,
                color = Color.White
            )

            Text(
                modifier = Modifier.constrainAs(energy_used) {
                    start.linkTo(avg_speed.end)
                    top.linkTo(avg_speed.top)
                    bottom.linkTo(avg_speed.bottom)
                    end.linkTo(efficiency.start)
                }, text = "Energy used",
                fontFamily = getAppFonts().inter,
                fontWeight = FontWeight.Medium,
                fontSize = 11.sp,
                color = getAppColors().textInActiveColor
            )

            Text(
                modifier = Modifier.constrainAs(energy_used_value) {
                    start.linkTo(energy_used.start)
                    top.linkTo(energy_used.bottom, 3.dp)
                    end.linkTo(energy_used.end)
                    bottom.linkTo(parent.bottom, 9.7.dp)
                },
                text = buildAnnotatedString {
                    withStyle(
                        style = SpanStyle(
                            fontWeight = FontWeight.SemiBold,
                            color = Color.White,
                            fontFamily = getAppFonts().inter,
                            fontSize = 12.sp,
                        )
                    ) {
                        append(domain?.tripSummary?.tripEnergyUsed ?: "")
                    }
                    append(" Wh")
                },
                fontSize = 11.sp,
                fontWeight = FontWeight.Medium,
                fontFamily = getAppFonts().inter,
                color = Color.White
            )

            Text(
                modifier = Modifier.constrainAs(efficiency) {
                    start.linkTo(energy_used.end)
                    top.linkTo(energy_used.top)
                    bottom.linkTo(energy_used.bottom)
                    end.linkTo(parent.end)
                }, text = "Efficiency",
                fontFamily = getAppFonts().inter,
                fontWeight = FontWeight.Medium,
                fontSize = 11.sp,
                color = getAppColors().textInActiveColor
            )

            Text(
                modifier = Modifier.constrainAs(efficiency_value) {
                    start.linkTo(efficiency.start)
                    top.linkTo(efficiency.bottom, 3.dp)
                    end.linkTo(efficiency.end)
                    bottom.linkTo(parent.bottom, 9.7.dp)
                },
                text =
                buildAnnotatedString {
                    withStyle(
                        style = SpanStyle(
                            fontWeight = FontWeight.SemiBold,
                            color = Color.White,
                            fontFamily = getAppFonts().inter,
                            fontSize = 12.sp,
                        )
                    ) {
                        append(domain?.tripSummary?.tripEfficiency ?: "")
                    }
                    append(" Wh/km")
                },
                fontSize = 11.sp,
                fontWeight = FontWeight.Medium,
                fontFamily = getAppFonts().inter,
                color = Color.White
            )


            if (painterState is ImagePainter.State.Loading) {
                CircularProgressIndicator(modifier = Modifier
                    .size(25.dp)
                    .constrainAs(progressBar) {
                        top.linkTo(map_image.top)
                        start.linkTo(map_image.start)
                        bottom.linkTo(map_legends_container.bottom)
                        end.linkTo(map_image.end)
                    }, color = Color.White
                )
            }


        }
    }`

**Comment by ShankarKakumani** [comment]
```
LazyColumn {

  list.forEachIndexed{ index, domain
  item {
  MainCard(index, domain)
  }
  }

}
```

**Comment by PatilShreyas** [comment]
I guess you're loading an image from the network? If yes, then you'll have to disable the hardware bitmap. [This is already mentioned in the documentation](https://github.com/PatilShreyas/Capturable#%EF%B8%8F-precaution).

**Comment by ShankarKakumani** [comment]
"So make sure not to include any UI content inside Composable which uses hardware bitmaps."

does this mean, I can only keep the network image in the ComposableFunction?

**Comment by PatilShreyas** [comment]
Just disable hardware rendering and it'll work as expected

**Comment by ShankarKakumani** [comment]
yeah, Just seen other issues where you explained about this

that we have to set allowHardware(false) in builder.
