### ISSUE TITLE
Save the captured image for upload to server

### ISSUE THREAD

**Issue by chkmls** [PatilShreyas/Capturable#58]
Is there a way to save the capture media as file?

**Comment by jsericksk** [comment]
What do you mean by "lower than original"?
I didn't experience this problem, but I believe that the quality of the final image may vary depending on the resolution size.
As for the image size, you can try lowering the quality in ```(bitmap.compress(Bitmap.CompressFormat.PNG, 90, outputStream)```. You can also try changing the format to JPEG, but it will probably result in a image with a slightly reduced quality.

**Comment by PatilShreyas** [comment]
The library is only intended for capturing composable content into bitmap. With file IO operations, you can save bitmap. 

See example: https://github.com/PatilShreyas/NotyKT/blob/master/noty-android/app/src/main/java/dev/shreyaspatil/noty/utils/FileUtils.kt

Closing this.
