### ISSUE TITLE
material3 card compatibility

### ISSUE THREAD

**Issue by Ruineie** [PatilShreyas/Capturable#92]
This tool is really helpful. But I found this issue with Card() in material3. When using this tool to capture a roundedcorner Card(), the screenshot isn't rounded, left white corner there. How can I fix this? Than you.

**Comment by PatilShreyas** [comment]
Hi, could you share a snippet? It would be helpful to provide a solution on this.

**Comment by PatilShreyas** [comment]
@Ruineie did it worked for you?

**Comment by PatilShreyas** [comment]
Closing this due to in-activity. Feel free to reopen with more details
