### ISSUE TITLE
It captures TextField's cursor too.

### ISSUE THREAD

**Issue by chanjungkim** [PatilShreyas/Capturable#99]
I am taking a capture with my custom TextField. 

And it captures the cursor too. 

And if I print it in the receipt printer(Only black&white), the transparent color look black. How can I solve this ?

**Comment by PatilShreyas** [comment]
Before capturing the snapshot, take focus out of TextField. Use `FocusRequester` for doing this.

**Comment by chanjungkim** [comment]
I solved this with focusClear(the cursor issue) and drawBehind & drawRect(Color.White). - modifier.background doesn't work.
